"""Initial migration.

Revision ID: d0bb8dbc47e0
Revises: 
Create Date: 2024-11-18 11:07:45.422059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bb8dbc47e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('img1', sa.String(length=500), nullable=True),
    sa.Column('img2', sa.String(length=500), nullable=True),
    sa.Column('img3', sa.String(length=500), nullable=True),
    sa.Column('img4', sa.String(length=500), nullable=True),
    sa.Column('img5', sa.String(length=500), nullable=True),
    sa.Column('img6', sa.String(length=500), nullable=True),
    sa.Column('img7', sa.String(length=500), nullable=True),
    sa.Column('img8', sa.String(length=500), nullable=True),
    sa.Column('img9', sa.String(length=500), nullable=True),
    sa.Column('img10', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_images_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('url_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.String(length=100), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['car_images.id'], name='fk_car_images_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_car_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('car_images')
    op.drop_table('user')
    # ### end Alembic commands ###
